### ISSUE TITLE
Wrong Constant in Code

### ISSUE THREAD

**Issue by GreenLightning** [PetterS/opencv_srgb_gamma#2]
When converting from sRGB to linear, the cutoff threshold should be 0.04045 instead of 0.4045.

References: [Wikipedia](https://en.wikipedia.org/wiki/SRGB), [GL_EXT_sRGB](https://www.khronos.org/registry/OpenGL/extensions/EXT/EXT_sRGB.txt)

Probably just a typo, but it's wrong in both versions:

https://github.com/PetterS/opencv_srgb_gamma/blob/bbebd5255f02de877032dd596b079e811ae85e25/srgb.h#L11

https://github.com/PetterS/opencv_srgb_gamma/blob/bbebd5255f02de877032dd596b079e811ae85e25/srgb.py#L6

**Comment by PetterS** [comment]
That is crazy! Thanks!

I guess I relied too much on visual inspection. The numeric tests were not good enough.
